package br.arraial.ICMBIO.telas;

import br.arraial.ICMBIO.telas.consultas.*;
import br.arraial.ICMBIO.telas.cadastros.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new Thread(new AtualizadorHora()).start();
            }
        });
    }

    private class AtualizadorHora implements Runnable {

        @Override
        public void run() {
            while (true) {
                try {
                    txtDate.setText(new SimpleDateFormat("HH:mm dd/MM/yyyy").format(new Date()));
                    Thread.sleep(500);
                } catch (InterruptedException exc) {
                    exc.printStackTrace();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnCentral = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        imCadModalidade = new javax.swing.JMenuItem();
        imCadEmbarcacao = new javax.swing.JMenuItem();
        imCadSolicitante = new javax.swing.JMenuItem();
        imCadUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        imConModalidade = new javax.swing.JMenuItem();
        imConEmbarcacao = new javax.swing.JMenuItem();
        imConSolicitante = new javax.swing.JMenuItem();
        imConUsuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        imSoliCadastro = new javax.swing.JMenuItem();
        imSoliConsulta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        imSaiCadastro = new javax.swing.JMenuItem();
        imSaiConsulta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ICMBio - Instituto Chico Mendes de Conservação da Biodiversidade");
        setResizable(false);

        pnCentral.setBackground(new java.awt.Color(255, 255, 255));
        pnCentral.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/arraial/ICMBIO/img/icmbio.jpg"))); // NOI18N

        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDate.setText("    ");
        txtDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDate.setOpaque(true);

        javax.swing.GroupLayout pnCentralLayout = new javax.swing.GroupLayout(pnCentral);
        pnCentral.setLayout(pnCentralLayout);
        pnCentralLayout.setHorizontalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCentralLayout.createSequentialGroup()
                .addContainerGap(541, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCentralLayout.setVerticalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCentralLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDate))
        );
        pnCentral.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnCentral.setLayer(txtDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Cadastro");

        imCadModalidade.setText("Modalidade");
        imCadModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCadModalidadeActionPerformed(evt);
            }
        });
        jMenu1.add(imCadModalidade);

        imCadEmbarcacao.setText("Embarcação");
        imCadEmbarcacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCadEmbarcacaoActionPerformed(evt);
            }
        });
        jMenu1.add(imCadEmbarcacao);

        imCadSolicitante.setText("Solicitante");
        imCadSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCadSolicitanteActionPerformed(evt);
            }
        });
        jMenu1.add(imCadSolicitante);

        imCadUsuario.setText("Usuário");
        imCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCadUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(imCadUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        imConModalidade.setText("Modalidade");
        jMenu2.add(imConModalidade);

        imConEmbarcacao.setText("Embarcação");
        imConEmbarcacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConEmbarcacaoActionPerformed(evt);
            }
        });
        jMenu2.add(imConEmbarcacao);

        imConSolicitante.setText("Solicitante");
        jMenu2.add(imConSolicitante);

        imConUsuario.setText("Usuário");
        jMenu2.add(imConUsuario);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Solicitação");

        imSoliCadastro.setText("Cadastro");
        imSoliCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imSoliCadastroActionPerformed(evt);
            }
        });
        jMenu3.add(imSoliCadastro);

        imSoliConsulta.setText("Consulta");
        imSoliConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imSoliConsultaActionPerformed(evt);
            }
        });
        jMenu3.add(imSoliConsulta);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Saida");

        imSaiCadastro.setText("Cadastro");
        imSaiCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imSaiCadastroActionPerformed(evt);
            }
        });
        jMenu5.add(imSaiCadastro);

        imSaiConsulta.setText("Consulta");
        jMenu5.add(imSaiConsulta);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ajuda");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCentral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCentral)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imConEmbarcacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConEmbarcacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imConEmbarcacaoActionPerformed

    private void imCadSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCadSolicitanteActionPerformed
        TelaCadSolicitante telasolicitante = new TelaCadSolicitante();
        pnCentral.add(telasolicitante);
        telasolicitante.show();
    }//GEN-LAST:event_imCadSolicitanteActionPerformed

    private void imCadModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCadModalidadeActionPerformed
        TelaCadModalidade telamodalidade = new TelaCadModalidade();
        pnCentral.add(telamodalidade);
        telamodalidade.show();
    }//GEN-LAST:event_imCadModalidadeActionPerformed

    private void imCadEmbarcacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCadEmbarcacaoActionPerformed
        TelaCadEmbarcacao telaembarcacao = new TelaCadEmbarcacao();
        pnCentral.add(telaembarcacao);
        telaembarcacao.show();
    }//GEN-LAST:event_imCadEmbarcacaoActionPerformed

    private void imCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCadUsuarioActionPerformed
        TelaCadUsuario telausuario = new TelaCadUsuario();
        pnCentral.add(telausuario);
        telausuario.show();
    }//GEN-LAST:event_imCadUsuarioActionPerformed

    private void imSaiCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imSaiCadastroActionPerformed
        TelaCadSaida telasaida = new TelaCadSaida();
        pnCentral.add(telasaida);
        telasaida.show();
    }//GEN-LAST:event_imSaiCadastroActionPerformed

    private void imSoliCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imSoliCadastroActionPerformed
        TelaCadSolicitacao telacadsol = new TelaCadSolicitacao();
        pnCentral.add(telacadsol);
        telacadsol.show();
    }//GEN-LAST:event_imSoliCadastroActionPerformed

    private void imSoliConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imSoliConsultaActionPerformed
        TelaConSolicitacao telaconsol = new TelaConSolicitacao();
        pnCentral.add(telaconsol);
        telaconsol.show();
    }//GEN-LAST:event_imSoliConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imCadEmbarcacao;
    private javax.swing.JMenuItem imCadModalidade;
    private javax.swing.JMenuItem imCadSolicitante;
    private javax.swing.JMenuItem imCadUsuario;
    private javax.swing.JMenuItem imConEmbarcacao;
    private javax.swing.JMenuItem imConModalidade;
    private javax.swing.JMenuItem imConSolicitante;
    private javax.swing.JMenuItem imConUsuario;
    private javax.swing.JMenuItem imSaiCadastro;
    private javax.swing.JMenuItem imSaiConsulta;
    private javax.swing.JMenuItem imSoliCadastro;
    private javax.swing.JMenuItem imSoliConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JDesktopPane pnCentral;
    private javax.swing.JLabel txtDate;
    // End of variables declaration//GEN-END:variables
}
