/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.arraial.ICMBIO.telas;

/**
 *
 * @author Aluno
 */
public class TelaSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaSobre
     */
    public TelaSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Este é um programa de gerenciamento que foi desenvolvido em Java para o ICMBIO, \numa instituição do governo brasileiro que gere e preserva a biodiversidade da fauna \ne flora brasileira, e em especial, controla o tráfego de embarcações na costa da Região \ndos Lagos, principalmente na cidade de Arraial do Cabo, Rio de Janeiro, Brasil.\n\nO objetivo do sistema é controlar o banco de dados de tráfego de embarcações do \nICMBIO com suporte a inserção, alteração, remoção e consulta de informações. Além \ndisso, o programa possui uma interface gráfica amigável desenvolvida com alguns \nrecursos da linguagem Java por conta do nosso público alvo, que são pessoas não \nnecessariamente ligadas à computação e tecnologia. O Sistema foi desenvolvido em \n3 camadas MVC (Model View Controler) e (OO) Orientado a Objetos.\n\nEsse projeto foi desenvolvido exclusivamente por alunos do IFRJ (Instituto Federal de \nEducação, Ciência e Tecnologia do Rio de Janeiro). Foi fruto da orientação do trabalho \nde conclusão do Curso Técnico em Meio Ambiente da aluna Emanuelle Ramos da Silva \nem parceria com a turma do 6º período do Ensino Médio Técnico em Informática, como \nforma de avaliação final da disciplina de Linguagens e Técnicas de Programação III.\n\nProfessor e Coordenador: Carlos Augusto Fernandes Filho, Mestre em Computação.\n\nIntegrantes da turma:\nAlberto Dinis Lira Figuerêdo, Gabriel Ribeiro, Philippe Loriot de Rouvray, Felipe Viana \nFalcão, Ariane Sales, Laura Fidalgo, Gabriel Carvalho da Silva Boalento, Anna \nCarolina Nicoli, Patrick Carmona, Gabrielli Ribeiro, Matheus Hiroshi Azuma Chavez , \nEmilly Rodrigues, Marcelo Coelho, Louise Lisboa, Abner Guedes, Maria Eduarda \nSoares, Bheatriz Syria, Euller Felipe Costa, Gabriella Caetano, Arthur Moreira, Raquel \nMoraes.");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/arraial/ICMBIO/img/ifrj.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
