/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.arraial.ICMBIO.telas;

/**
 *
 * @author Aluno
 */
public class TelaSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaSobre
     */
    public TelaSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Este é um programa de gerenciamento que foi desenvolvido em Java para o \nICMBIO, uma instituição do governo brasileiro que gere e preserva a biodiversidade da \nfauna e flora brasileira, e em especial, controla o tráfego de embarcações na costa da \nRegião dos Lagos, principalmente em Arraial do Cabo, Rio de Janeiro, Brasil, para onde \niremos desenvolver o programa.\n\nO objetivo do programa é controlar o banco de dados de tráfego de embarcações do \nICMBIO com suporte a inserção, alteração e remoção de informações. Além disso, o \nprograma possui uma interface gráfica amigável desenvolvida com alguns recursos \nda linguagem Java por conta do nosso público alvo, que são pessoas não necessaria-\nmente ligadas à computação e tecnologia.\n\nEsse programa será desenvolvido em colaboração por uma turma do 6º período do \nEnsino Médio Técnico em informática do IFRJ como forma de avaliação final do período \npara a disciplina Linguagens de Programação III. Apesar de parte dessa descrição ter \nsido escrita em inglês, todos os commits e outros comentários serão escritos em \nportuguês de modo a facilitar nossa comunicação, já que é nossa língua materna e \nnem todos nós falamos inglês.\n\nProfessor: Carlos Augusto Fernandes, Mestre em Computação.\n\nIntegrantes da turma: \n\nAlberto Dinis Lira Figuerêdo, Gabriel Ribeiro, Philippe Loriot de Rouvray, Felipe Viana \nFalcão, Ariane Sales, Laura Fidalgo, Gabriel Carvalho da Silva Boalento, Anna \nCarolina Nicoli, Patrick Carmona, Gabrielli Ribeiro, Matheus Hiroshi Azuma Chavez , \nEmilly Rodrigues, Marcelo Coelho, Louise Lisboa, Abner Guedes, Maria Eduarda \nSoares, Bheatriz Syria, Euller Felipe Costa, Gabriella Caetano, Arthur Moreira, Raquel \nMoraes.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/arraial/ICMBIO/img/ifrj.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
